class Scatter:
    def __init__(self, *args: object, **kwargs: object) -> None: ...


class Figure:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def add_trace(self, trace: object) -> None: ...
    def update_layout(self, **kwargs: object) -> None: ...
    def show(self) -> None: ...


class Layout:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
